#!/bin/bash
#@author Vinicius O. Queiroz

/bin/epson-projector-cmd poweron
echo "teste"
echo -e "\x0D*pow=on#\x0D" > /dev/ttyS1
sleep 1

/bin/epson-projector-cmd sendcmd "SOURCE 1F"
echo -e "\x0D*auto\x0D" > /dev/ttyS1
sleep 1

echo -e "\x0D*baud=9600\x0D" > /dev/ttyS1

exit
