#!/bin/bash
vendor=$(cat /lib/lampada-projetor-proinfo-libs/vendor)

isReboot=$(systemctl list-jobs | grep 'reboot.target')

if [ "$isReboot" == "" ]; then

         case $vendor in
           "epson") # If the projector manufacturer is Epson.
             /bin/epson-projector-cmd poweroff
           ;;
           
           *) # If the projector manufacturer is benq or others.
             echo -e "\x0D*pow=off#\x0D" > /dev/ttyS1
           ;;
           
         esac
fi
exit
