#!/bin/bash
isReboot=$(systemctl list-jobs | grep 'reboot.target')

if [ "$isReboot" == "" ]; then
             /bin/epson-projector-cmd poweroff
             echo -e "\x0D*pow=off#\x0D" > /dev/ttyS1
fi
exit
