#!/bin/bash
#Permissão de Execução
   chmod +x /bin/epson-projector-cmd
   chmod +x /usr/lampada-proinfo-ctl/projetor-o*

# Garantindo participacao no grupo dialout
   adduser professor dialout
   adduser root dialout
# Iniciando Servicos
   systemctl enable projetor-on.service
   systemctl enable projetor-off.service
   systemctl start projetor-off.service
