#!/bin/bash
#Iniciando os serviços SystemD

if [ "$(id -u)" = "0" ]; 
then
# Garantindo participacao no grupo dialout
   adduser professor dialout
   adduser root dialout
# Iniciando Servicos
   systemctl enable projetor-on.service
   systemctl enable projetor-off.service
   systemctl start projetor-off.service
else
   echo "Execute como superusuário 'root'"
fi
exit
