#!/bin/bash
users >> /tmp/usuarios
for user in `/tmp/usuarios`; do
useradd -m -d /home/$user -p '$1$VG5IN8yj$Oh/gNwn5QsGhmZ9ZeUGrp1' $user
adduser $user dialout
done

echo "Digite 'epson' (sem aspas) caso o seu projetor seja um 71/2013 ou se voce tiver certeza de que o fabricante da lampada é Epson:"
echo "Ou digite 'benq' (sem aspas) caso o seu projetor seja um 42/2010 ou se voce tiver certeza de que o fabricante da lampada é a Benq:"
echo "Digite abaixo ..."
read fabricante
echo $fabricante > /lib/lampada-projetor-proinfo-libs/fabricante
echo "OK. Você possui um Projetor" $fabricante
